import type { Metadata } from "next";
import  "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Pokenext",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        <main className="main-container">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}